on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: 8
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run ./gradlew --no-daemon check
        run: ./gradlew --no-daemon check